FROM hyperf/hyperf:8.3-alpine-v3.19-swoole AS php_base

ARG timezone

ENV TIMEZONE=${timezone:-"Europe/Moscow"}
RUN set -ex \
    && php -v \
    && php -m \
    && php --ri swoole \
    && ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && echo "${TIMEZONE}" > /etc/timezone

RUN set -ex \
    && apk update \
    && apk add --no-cache \
        mc git curl wget unzip nano make bash autoconf g++ make \
        postgresql-client postgresql-dev \
        libpq libpq-dev libsodium \
        php83-dev php83-pdo php83-pdo_pgsql php83-pgsql php83-pcntl \
        php83-sockets php83-redis php83-pecl-ds php83-pecl-igbinary \
    && cd /tmp \
    && rm -rf /tmp/* /var/cache/apk/* /usr/share/man /usr/share/doc

ENV COMPOSER_ALLOW_SUPERUSER=1
ENV COMPOSER_HOME=/tmp
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ENV PATH=/app/vendor/bin:/usr/local/bin:${PATH}

WORKDIR /app

COPY docker/php/conf.d/hyperf.ini /etc/php83/conf.d/991-hyperf.ini

EXPOSE 9501

FROM php_base AS php_dev

ENV APP_ENV=dev
ENV SCAN_CACHEABLE=false

COPY docker/php/conf.d/hyperf.dev.ini /etc/php83/conf.d/992-hyperf-dev.ini

FROM php_base AS php_production

ENV APP_ENV=production
ENV SCAN_CACHEABLE=true

COPY docker/php/conf.d/hyperf.prod.ini /etc/php83/conf.d/992-hyperf-prod.ini

FROM php_base AS composer

CMD ["composer", "install"]
